name: rebuttal-agent
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.5
  - openssl=3.5.1
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.10.18
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tmux=3.5
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - accelerate==1.8.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - airportsdata==20250622
      - annotated-types==0.7.0
      - anyio==4.9.0
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrs==25.3.0
      - blake3==1.0.5
      - cachetools==5.5.2
      - certifi==2025.6.15
      - cffi==1.17.1
      - chardet==3.0.4
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - compressed-tensors==0.10.1
      - contourpy==1.3.2
      - cryptography==45.0.6
      - cupy-cuda12x==13.4.1
      - cycler==0.12.1
      - datasets==3.6.0
      - deprecated==1.2.18
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - einops==0.8.1
      - email-validator==2.2.0
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.0
      - fastapi==0.115.14
      - fastapi-cli==0.0.7
      - fastrlock==0.8.3
      - filelock==3.18.0
      - fonttools==4.58.4
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - future==1.0.0
      - gguf==0.17.1
      - google-auth==2.40.3
      - google-genai==1.25.0
      - googleapis-common-protos==1.70.0
      - grpcio==1.73.1
      - h11==0.16.0
      - h2==4.3.0
      - hf-xet==1.1.4
      - hpack==4.1.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.33.0
      - hyperframe==6.1.0
      - idna==2.8
      - ijson==3.4.0
      - importlib-metadata==8.7.0
      - interegular==0.3.3
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - lark==1.2.2
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.11
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.5
      - mdurl==0.1.2
      - mistral-common==1.6.2
      - modelscope==1.29.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - msgspec==0.19.0
      - multidict==6.5.0
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.3
      - ninja==1.11.1.4
      - numba==0.61.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - openai==1.90.0
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.5
      - openreview==0.0.2
      - openreview-py==1.51.2
      - opentelemetry-api==1.34.1
      - opentelemetry-exporter-otlp==1.34.1
      - opentelemetry-exporter-otlp-proto-common==1.34.1
      - opentelemetry-exporter-otlp-proto-grpc==1.34.1
      - opentelemetry-exporter-otlp-proto-http==1.34.1
      - opentelemetry-proto==1.34.1
      - opentelemetry-sdk==1.34.1
      - opentelemetry-semantic-conventions==0.55b1
      - opentelemetry-semantic-conventions-ai==0.4.9
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==25.0
      - pandas==2.3.0
      - partial-json-parser==0.2.1.1.post6
      - pdfdeal==1.0.2
      - pdfminer==20191125
      - pdfminer-six==20250506
      - pillow==11.2.1
      - prometheus-client==0.22.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.2
      - protobuf==5.29.5
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==20.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycountry==24.6.1
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pylatexenc==2.10
      - pyparsing==3.2.3
      - pypdf==6.0.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - ray==2.47.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.5
      - rich==14.0.0
      - rich-toolkit==0.14.8
      - rpds-py==0.25.1
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentence-transformers==5.0.0
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.46.2
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==8.5.0
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - tld==0.13.1
      - tokenizers==0.21.2
      - torch==2.7.0
      - torchaudio==2.7.0
      - torchvision==0.22.0
      - tqdm==4.67.1
      - transformers==4.53.0
      - triton==3.3.0
      - typer==0.16.0
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - vllm==0.9.1
      - watchfiles==1.1.0
      - websockets==15.0.1
      - wrapt==1.17.3
      - xformers==0.0.30
      - xgrammar==0.1.19
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /home/zongwei11/anaconda3/envs/rebuttal-agent
